version: 2.1

commands:
  sayhello:
    description: 'Say hello reusable command'
    parameters:
      to:
        type: string
    steps:
      - run:  echo << parameters.to >>

jobs:
  build:
    docker:
      - image: node:alpine
    steps:
      - run: apk add git #base image does not have git
      - checkout
      - run:
          name: The first step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
      - run:
          name: Code has arrived
          command: |
            ls -al
            echo '^^^That should look familiar^^^'
      - run: node -v

  test:
    docker:
      - image: node:alpine
    steps:
      - sayhello: {to: vadim}
      - run: echo "This is test"

workflows:
  version: 2
  'Test and build':
    jobs:
      - build
      - test: {requires: [ build ]}
      - 'Hold for approval': {type: approval, requires: [ build, test ]}

  'Test only':
    jobs:
      - test


